import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Launchpad Crowdsales
        </h1>

        <p className={styles.description}>
          Get started with Launchpad
        </p>

        <div className={styles.grid}>
          <a href="/proposals" className={styles.card}>
            <h2> Proposal &rarr;</h2>
            <p>Propose to run your own Launchpad campaign</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Contribute &rarr;</h2>
            <p>Contribute to a Launchpad campaign</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Proposals &rarr;</h2>
            <p>View Launchpad proposals</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Campaigns &rarr;</h2>
            <p> View Launchpad campaigns</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
