import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getApiProvider from "./api/getApiProvider";
import { Keyring } from '@polkadot/api';
import { CampaignInfo, CurrencyId } from "@setheum.js/types/interfaces"

export async function getProposal() {
  const api = await getApiProvider();

  const currencyId = { TOKEN: "SERP" };

  const keyring = new Keyring({type: 'sr25519'});

  const alice = keyring.addFromUri('//Alice');

  const info = (await api.query.launchPad.proposals(currencyId));
  console.log("Campaign Info", info.toHuman());
  return info;
};

const Proposals: NextPage = () => {
  console.log('info', getProposal());
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Launchpad Proposals
        </h1>

        <p className={styles.description}>
          Get started with Launchpad
        </p>

        <ul className={styles.grid}>
          <li className={styles.card}>
            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
            >
              <h2>My Proposal &rarr;</h2>
              <p>View Launchpad proposals</p>
            </a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Proposals
